### ISSUE TITLE
Update PhantomJS to version 2.1

### ISSUE THREAD

**Issue by belyan** [marcbachmann/node-html-pdf#106]
Please, update PhantomJS to version 2.1.
This will fix the problem with the hyperlinks, which is described in the issue #26.

**Comment by Lichtjaeger** [comment]
Jes, please. You only have to update the version number of the `phantomjs`-module in the `package.json` to `^2.1.3`.

PS: There is a notice in the `README.md` of the `phantomjs`-module to rename it to `phantomjs-prebuilt`.

**Comment by marcbachmann** [comment]
I almost released v2 with phantomjs v2. But then I saw that the font in the examples is not the same size anymore. Do you know whether they changed the pixel-to-inches ratio in phantomjs? Or something else?

> Please, update PhantomJS to version 2.1.

Finally. That wasn't fixed in 2.0. One reason I didn't upgrade yet is that the phantomjs node module didn't upgrade to phantomjs 2. They released the new version only 4 days ago.

**Comment by marcbachmann** [comment]
I've just published `html-pdf@2.0.0`
