### ISSUE TITLE
Pass parameters to html

### ISSUE THREAD

**Issue by molerat619** [marcbachmann/node-html-pdf#200]
Is there a way to pass parameters to the html doc that should be transformed to a pdf?

**Comment by adentranter** [comment]
Are you wanting to template the HTML before transforming it into a PDF? IE load dynamic data into the PDF.

I am using underscore to do this, So i have my html template and then run it through underscore and it fills in the data. I then pass that processed HTML to the PDF convert.

Is this what you mean?

**Comment by molerat619** [comment]
Yeah, basically that's what I mean. Intuitively I would do string operations on the html code and replace {{variable}} with the values. But I thought maybe there is something nicer implement here.

**Comment by marcbachmann** [comment]
That isn't in the scope of this module.
Please use a preprocessor and call that before calling this module.

**Comment by maxmarkus** [comment]
@molerat619 have a look at  http://www.embeddedjs.com which a nice template engine with a small footprint. 
You might want to close this issue too afterwards.

**Comment by musso** [comment]
@marcbachmann  @molerat619 
Actually it's not hard to implement it ... it's just like passing the contents to the header and footer

**Comment by olefrank** [comment]
Could you please provide a simple example of this?

**Comment by molerat619** [comment]
For another use case that was even more complex, I actually used embeddedjs in the end and it worked absolutely fine - I can recommend it.

**Comment by olefrank** [comment]
Thanks I actually got it working with lodash templates :)

Another question: I want to separate out the car into a separate local file
but I can't load it. The styles isn't applied. The example you provide is a
remote stylesheet but I need to load a local file.

How can I load a local stylesheet?

Cheers
Ole

Den 6. jul. 2017 11.58 skrev "Marcel Izgin" <notifications@github.com>:

**Comment by olefrank** [comment]
Thanks I actually got it working with lodash templates :)

Another question: I want to separate out the css into a separate local file
but I can't load it. The styles isn't being applied to document when coming
from a local file. They only work when put directly in head tag. The
example you provide is a remote stylesheet but I need to load a local file.

How can I load a local stylesheet?

Cheers
Ole

Den 6. jul. 2017 11.58 skrev "Marcel Izgin" <notifications@github.com>:

For another use case that was even more complex, I actually used embeddedjs
in the end and it worked absolutely fine - I can recommend it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/marcbachmann/node-html-pdf/issues/200#issuecomment-313352473>,
or mute the thread
