### ISSUE TITLE
Sending PDF file as response to client

### ISSUE THREAD

**Issue by mmoman1993** [marcbachmann/node-html-pdf#304]
I am Using Express JS and I want to generate PDF File from HTML File then I want to send it to the client 
how is that possible ?

**Comment by alex-bashkatov-ezlo** [comment]
Inside request handler
```js
pdf.create(html, { format: 'Letter' }).toStream(function(err, stream) {
        if (err) {
          res.json({
            message: 'Sorry, we were unable to generate pdf',
          });
        }

       stream.pipe(res);
});
```

**Comment by guillermo-medina** [comment]
I don't know if this is related but I have a backend function where i convert a HTML to PDF. The problem i'm having is: I have an array of posts. When I start to loop into this array, i call the pdf.create().toStream() function. Then, I zip this pdfs and send to the browser to download. The problem here is... pdf.create().toStream() is async and the post name and file name are different. How I can convert the pdf.create.... to a sync method to wait until finish the conversion to start with the next one?

Thanks in advance.

**Comment by starcraft0429** [comment]
hi @alex-bashkatov-ezlo 
I can receive text data in client side like below
```
%PDF-1.4
1 0 obj
<<
/Title (��)
/Creator (��)
/Producer (��
...
```

how can I display pdf with this in browser?

**Comment by marcbachmann** [comment]
I've added an example here: https://github.com/marcbachmann/node-html-pdf/blob/master/examples/serve-http/index.js

> How I can convert the pdf.create.... to a sync method to wait until finish the conversion to start with the next one?

```js
const async = require('async') // http://npm.im/async
const pdf = require('html-pdf')

async.map(['foo', 'bar'], function (el, done) {
  pdf.create(el).toFile(done)
}, function (err, results) {
  if (err) throw err
  console.log(results) // results is probably [{file: '/tmp/path-to-first'}, {file: '/tmp/path-to-second'}]
})
```

**Comment by jatinderbhola** [comment]
> hi @alex-bashkatov-ezlo
> I can receive text data in client side like below
> 
> ```
> %PDF-1.4
> 1 0 obj
> <<
> /Title (��)
> /Creator (��)
> /Producer (��
> ...
> ```
> how can I display pdf with this in browser?

did you find any solution? I am facing the same issue.

**Comment by jasp402** [comment]
I too...

**Comment by kinkladze28** [comment]
me too

**Comment by dejanstrancar** [comment]
@starcraft0429 you need to set header before stream.pipe

`res.setHeader('Content-Type', 'application/pdf');`

Hope that helps
