### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [marcbachmann/node-html-pdf#496]
Hi, what is the current status of this project? Is it still maintained?

**Comment by marcbachmann** [comment]
Sorry, I don't have any time and motivation to maintain this project as I don't use it anywhere anymore.

By now puppeteer also properly supports headers and footers, so I'd suggest to migrate to that as it's also much faster and has better html & css support.

Migrating this library to something that supports a worker pool would result in a breaking change anyways.

**Comment by iyerusad** [comment]
@marcbachmann Might be worthwhile to update Readme.md/archive project, noting project is no longer maintained (presumably shouldn't be maintained either since core dependency, phantomJS [is no longer being maintained](https://github.com/ariya/phantomjs/issues/15344)). Package still gets a fair bit of traffic.

Some alternatives might be worth noting (from [npm search engine --optimal flag](https://www.npmjs.com/search?ranking=optimal&q=html%20pdf)):
- https://www.npmjs.com/package/electron-pdf
- https://www.npmjs.com/package/pdf-puppeteer
- https://www.npmjs.com/package/prince
- https://www.npmjs.com/package/html2pdf.js

Thank you for making this though - html to pdf is still an area of need even in 2020, much less when the project originally put together.

**Comment by ghonchesefidi** [comment]
@marcbachmann Can I update the readme file about project status and introduce some alternatives?
