### ISSUE TITLE
Is it possible not to create tmp files but use streams internally?

### ISSUE THREAD

**Issue by IonicaBizau** [marcbachmann/node-html-pdf#61]
From what I saw this library creates temporary files and probably pipes them from there.

Is it possible not to create them?

**Comment by marcbachmann** [comment]
An earlier version of html-pdf (https://github.com/marcbachmann/node-html-pdf/commit/bc639bfea1596c3c5f0ebb6243c5e44e0601dd11) supported that. But that was buggy on windows and didn't work on some other systems. That's why I've removed it completely.
I can have a look at that again in phantomjs 2. Maybe the stdoutput in there got better.

**Comment by IonicaBizau** [comment]
That would be handy. 

I opened an issue here as well: https://github.com/sgentle/phantomjs-node/issues/302

I was worrying if Heroku allows writing in the tmp dir, and it does. So, it's not a big issue (https://github.com/IonicaBizau/nodeice/pull/5). :smile:
